services:
  langfuse-worker:
    image: olegkarenkikh/langfuse_langfuse-worker:4
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      DIRECT_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_AUTH: ${REDIS_PASSWORD:-}
      SALT: ${SALT:-changeme}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-0000000000000000000000000000000000000000000000000000000000000000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-changeme}
      # Отключение ClickHouse
      CLICKHOUSE_MIGRATION_URL: ""
      CLICKHOUSE_URL: ""
      LANGFUSE_AUTO_CLICKHOUSE_MIGRATION_DISABLED: "true"

  langfuse-web:
    image: olegkarenkikh/langfuse:web1
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      DIRECT_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_AUTH: ${REDIS_PASSWORD:-}
      SALT: ${SALT:-changeme}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-0000000000000000000000000000000000000000000000000000000000000000}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-changeme}
      NEXTAUTH_URL: http://localhost:3000
      # Отключение ClickHouse
      CLICKHOUSE_MIGRATION_URL: ""
      CLICKHOUSE_URL: ""
      LANGFUSE_AUTO_CLICKHOUSE_MIGRATION_DISABLED: "true"
      NEXT_TELEMETRY_DISABLED: 1

  redis:
    image: docker.io/redis:7-alpine
    restart: always
    command: >
      sh -c "redis-server ${REDIS_PASSWORD:+--requirepass \"$$REDIS_PASSWORD\"}"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - langfuse_redis_data:/data
    healthcheck:
      test: 
        - CMD
        - sh
        - -c
        - "redis-cli ${REDIS_PASSWORD:+-a \"$$REDIS_PASSWORD\"} ping | grep PONG"
      interval: 3s
      timeout: 10s
      retries: 10

  postgres:
    image: docker.io/postgres:16-alpine
    restart: always
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data

volumes:
  langfuse_postgres_data:
    driver: local
  langfuse_redis_data:
    driver: local
